### ISSUE TITLE
python3 cyberinfo.pyo not working 

### ISSUE THREAD

**Issue by Pentasher** [AnonymousAt3/cyberinfo#1]
When I type this command, it says "File "cyberinfo.pyo", line 1
SyntaxError: Non-UTF-8 code starting with '\xf3' in file cyberinfo.pyo on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details". Any help!

**Comment by AnonymousAt3** [comment]
python2 cyberinfo.pyo

**Comment by AnonymousAt3** [comment]
python2 cyberinfo.py
